server:
  port: 8080

spring:
  application:
    name: seckill-lab
  profiles:
    default: v2

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: info
